---
# DO NOT commit real secrets to git.
apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eW91ci1yb290LXBhc3N3b3Jk      
  MYSQL_PASSWORD:      dGFza2Zsb3dfcGFzc3dvcmQ=        
  SECRET_KEY:          hVPTNh9RTSlYLU9TPYZCUz+U1t78yDoh/I5eJ3jqwuM= 
